In [1]:
#!./pre_env.sh mxnet
#!pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/
#!pip config set install.trusted-host mirrors.aliyun.com
#!pip install -U pip
#!pip install mxnet-mkl
#!pip install gluoncv
#!pip install gluonnlp
#!pip install autogluon

## NDArray

In [2]:
from mxnet import nd

#导入/导出

#创建
o = nd.array([1,2,3]);     print(o)      # 一维数组，
t = nd.array([(1,2,3),(4,5,6)]); print(t)# 二维数组，
z = nd.zeros(6);           print(z)      # 一维数组，全零
l = nd.linspace(0,10,6);   print(l)      # 一维数组，等分
r = nd.arange(0,10,3);     print(r)      # 一维数组，步长 
i = nd.eye(5);             print(i)      # 单位矩阵
f = nd.full((2,3), 0);     print(f)      # 多维数组，zeros(6), reshape(2,3)
s = nd.random.randn(4, 5); print(s)

#查看属性
#print(a.shape, b.shape, c.shape)

#拷贝/排序/变形

#增加/删除元素

#组合/分离

#索引/切片/子集

#标量计算

#向量计算

#统计


[1. 2. 3.]
<NDArray 3 @cpu(0)>

[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>

[0. 0. 0. 0. 0. 0.]
<NDArray 6 @cpu(0)>

[ 0.  2.  4.  6.  8. 10.]
<NDArray 6 @cpu(0)>

[0. 3. 6. 9.]
<NDArray 4 @cpu(0)>

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<NDArray 5x5 @cpu(0)>

[[0. 0. 0.]
 [0. 0. 0.]]
<NDArray 2x3 @cpu(0)>

[[ 2.2122064   0.7740038   1.0434403   1.1839255   1.8917114 ]
 [-1.2347414  -1.771029   -0.45138445  0.57938355 -1.856082  ]
 [-1.9768796  -0.20801921  0.2444218  -0.03716067 -0.48774993]
 [-0.02261727  0.57461417  1.4661262   0.6862904   0.35496104]]
<NDArray 4x5 @cpu(0)>
